name: ci-zoho-attendance
on: 
  push:
    branches: 
      - main

jobs:
  pull-new-code:
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          cd $GITHUB_WORKSPACE
          ls
      # - run: cd $GITHUB_WORKSPACE
      # - run: source .venv/bin/activate
      # - run: pip install -r requirements.txt