name: ci-zoho-attendance
on: 
  push:
    branches: 
      - main

jobs:
  pull-new-code:
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - uses: actions/checkout@v3
      - run: cd zoho/zoho
      - run: source .venv/bin/activate
      - run: pip install -r requirements.txt