name: ci-zoho-attendance
on: 
  push:
    branches: 
      - main

jobs:
  pull-new-code:
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - uses: actions/checkout@v3
      - name: Install virtualenv and libs
        run: |
          cd $GITHUB_WORKSPACE
          python3.8 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Create config
        # env: 
        #   USERNAME: 
        #   PASSWORD: 
        #   TOTP: 
        run: |
          cd $GITHUB_WORKSPACE
          mkdir src/config
          cd src/config
          touch config.ini
          echo "[default]" >> config.ini
          echo ZOHO_USERNAME='${{ secrets.ZOHO_USERNAME }}' >> config.ini
          echo ZOHO_PASSWORD='${{ secrets.ZOHO_PASSWORD }}' >> config.ini
          echo ZOHO_TOTP='${{ secrets.ZOHO_TOTP }}' >> config.ini
      # - run: cd $GITHUB_WORKSPACE
      # - run: source .venv/bin/activate
      # - run: pip install -r requirements.txt