name: ci-zoho-attendance
on: 
  push:
    branches: 
      - main

jobs:
  pull-new-code:
    runs-on: ["self-hosted", "linux", "x64"]
    steps:
      - uses: actions/checkout@v3
      - name: Install virtualenv and libs
        run: |
          cd $GITHUB_WORKSPACE
          python3.10 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
      - name: Create config
        env: 
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          TOTP: ${{ secrets.TOTP }}
        run: |
          cd $GITHUB_WORKSPACE
          mkdir src/config
          cd src/config
          touch config.ini
          echo USERNAME="$USERNAME" >> config.ini
          echo PASSWORD="$PASSWORD" >> config.ini
          echo TOTP="$TOTP" >> config.ini
      # - run: cd $GITHUB_WORKSPACE
      # - run: source .venv/bin/activate
      # - run: pip install -r requirements.txt